#ifndef POLY_HPP
#define POLY_HPP

#include <ap_int.h>
#include <hls_stream.h>

// Generated by the build's gen_include step from poly_schema.py.  Each
// schema becomes a struct with methods that read and write it as AXI4-Stream
// words; float32_array_utils does the same for arrays of float samples.
#include "include/streamutils_hls.h"
#include "include/float32_array_utils.h"
#include "include/poly_error.h"
#include "include/coeff_array.h"
#include "include/poly_cmd_hdr.h"
#include "include/poly_resp_hdr.h"
#include "include/poly_resp_ftr.h"

// The stream word width, in bits.  run.tcl sets it with -DWORD_BW=...; a
// 32-bit word carries one float sample, a 64-bit word carries two.
#ifndef WORD_BW
#define WORD_BW 32
#endif
static_assert(WORD_BW == 32 || WORD_BW == 64, "WORD_BW must be 32 or 64");

using axis_word_t = streamutils::axi4s_word<WORD_BW>;

void poly(hls::stream<axis_word_t>& in_stream, hls::stream<axis_word_t>& out_stream);

#endif  // POLY_HPP
